version: '3.8'
services:
  produit_service:
    build: ./produit_service
    ports:
      - '3001:3000'
    depends_on:
      - mongodb

  fournisseur_service:
    build: ./fournisseur_service
    ports:
      - '3002:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.23
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: